# Windows (https://github.com/travis-ci-tester/toolchain-table)
os: Windows Server 2017
install:
  - cinst cmake.portable wget 7zip.commandline
  # Install Windows Installer XML (WiX) to create installer with cpack
  # This package is currently broken because of a missing checksum. Since we
  # are not distributing the packages, we don't care about that and can
  # override the checksum:
  - choco feature enable -n allowEmptyChecksums
  - cinst wixtoolset
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
cache:
  - C:\Users\appveyor\.gradle
environment:
  matrix:
    ###
    - TOOLCHAIN: "default"
      CONFIG: Release

    - TOOLCHAIN: "default"
      CONFIG: Debug

    # ###
    # - TOOLCHAIN: "ninja-vs-12-2013-win64"
    #   CONFIG: Release

    # - TOOLCHAIN: "ninja-vs-12-2013-win64"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "nmake-vs-12-2013-win64"
    #   CONFIG: Release

    # - TOOLCHAIN: "nmake-vs-12-2013-win64"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "nmake-vs-12-2013"
    #   CONFIG: Release

    # - TOOLCHAIN: "nmake-vs-12-2013"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "vs-10-2010"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-10-2010"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "vs-11-2012"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-11-2012"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "vs-12-2013-win64"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-12-2013-win64"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "vs-12-2013-xp"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-12-2013-xp"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "vs-12-2013"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-12-2013"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "vs-14-2015"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-14-2015"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "vs-9-2008"
    #   CONFIG: Release

    # - TOOLCHAIN: "vs-9-2008"
    #   CONFIG: Debug

    # ###
    # - TOOLCHAIN: "mingw"
    #   CONFIG: Release

    # - TOOLCHAIN: "mingw"
    #   CONFIG: Debug

build_script:
  - cmd: cd tagfinderui
  - cmd: gradlew.bat jfxnative
  - cmd: cd build\jfx\native
  - cmd: dir 

artifacts:
  - path: C:\projects\universaltagfinder\tagfinderui\build\dist\jar\lib
    name: lib

  - path: C:\projects\universaltagfinder\tagfinderui\build\dist\jar\*.jar
    name: jar

  - path: C:\projects\universaltagfinder\tagfinderui\build\dist\native\*
    name: native